FROM python:3-alpine

WORKDIR /server
COPY ./server/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ./server ./

WORKDIR /
ENTRYPOINT [ "/server/start_server.sh" ]

